# 背景半透明，方便抄代码
window:
  opacity: 0.7

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

# Colors (Pencil Light)
colors:
  # Default Colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'
  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#bd93f9'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bbbbbb'
  # Bright colors
  bright:
    black:   '#44475a'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#bd93f9'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#ffffff'

# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
font:
  size: 9

  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code

  italic:
    family: Fira Code
