# Colors (Snazzy)
colors:
  # Default colors
  primary:
    # background: '0x282a36'
    background: '0x000000'
    foreground: '0xeff0eb'
    # foreground: '0x282a36'

  # Normal colors
  normal:
    black:   '0x282a36'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'

  # Bright colors
  bright:
    black:   '0x686868'
    red:     '0xff5c57'
    green:   '0x5af78e'
    yellow:  '0xf3f99d'
    blue:    '0x57c7ff'
    magenta: '0xff6ac1'
    cyan:    '0x9aedfe'
    white:   '0xf1f1f0'


# Font Settings
font:
  normal:
    family: Fira Code   #alacritty显示的字体样式
  bold:
    family: Fira Code
  italic:
    family: Fira Code
  size: 6.5                    #字体大小


# Opacity Setting
background_opacity: 0.7       #窗口透明度

